### ISSUE TITLE
Example does not work with different DFT size

### ISSUE THREAD

**Issue by LukasDrude** [ehabets/INF-Generator#1]
I was experimenting with you code recently. Thank you for providing this insightful code.

In the following lines, you call the `mycoherence()` function with additional parameters, e.g., `NFFT`:

- [test_sphere.m#L53](https://github.com/ehabets/INF-Generator/blob/5e4971c089851e82aa6c9cd62db60fa48d884036/test_sphere.m#L53)
- [test_cylinder.m#L52](https://github.com/ehabets/INF-Generator/blob/master/test_cylinder.m#L52)

However, the function does not accept additional parameters and always keeps `NFFT=256`:
[mycohere.m#L50](https://github.com/ehabets/INF-Generator/blob/master/mycohere.m#L50)

Another easy problem to fix is, that the Matrix `sc_sim` is initialized too small:

- [test_sphere.m#L50](https://github.com/ehabets/INF-Generator/blob/master/test_sphere.m#L50)
- [test_cylinder.m#L49](https://github.com/ehabets/INF-Generator/blob/master/test_cylinder.m#L49)

It should much rather be:
`sc_sim = zeros(M-2,NFFT/2+1);`

**Comment by ehabets** [comment]
The issues have been resolved. Thank you for the feedback!
